export const OBJECT_TYPES = [
    "Bed",
    "Nightstand",
    "Dresser",
    "Wardrobe",
    "Chair",
    "Desk",
    "Bookshelf",
    "Lamp",
    "Window",
    "Door",
    "Closet",
    "TV_Stand",
    "Mirror",
    "Rug",
    "Plant",
    "Wall_Art",
    "Curtains",
    "Sofa",
    "Coffee_Table",
    "Side_Table",
    "Dining_Table",
    "Kitchen_Counter",
    "Kitchen_Island",
    "Refrigerator",
    "Stove",
    "Sink",
    "Bathroom_Vanity",
    "Toilet",
    "Shower",
    "Bathtub",
]

export const DEFAULT_OBJECTS_JSON = []

export const RESIZE_HANDLES = [
    { position: "top-left", cursor: "nwse-resize" },
    { position: "top", cursor: "ns-resize" },
    { position: "top-right", cursor: "nesw-resize" },
    { position: "right", cursor: "ew-resize" },
    { position: "bottom-right", cursor: "nwse-resize" },
    { position: "bottom", cursor: "ns-resize" },
    { position: "bottom-left", cursor: "nesw-resize" },
    { position: "left", cursor: "ew-resize" },
] as const

